name: bird-bone-ai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python version requirement
  - python=3.11.*

  # Core system packages
  - pip
  - git
  - git-lfs

  # PyTorch with CUDA (conda for better dependency resolution)
  - pytorch=2.4.*
  - torchaudio=2.4.*  
  - torchvision=0.19.*
  - pytorch-cuda=12.4

  # Scientific computing foundation
  - numpy>=1.24.0
  - scipy>=1.11.0

  # Development tools (conda versions for better integration)
  - jupyter
  - jupyterlab>=4.2.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # System utilities
  - curl
  - wget
  - unzip

  # Optional: CUDA development tools (uncomment if needed for custom kernels)
  # - cudatoolkit-dev=12.4
  # - nvidia-cuda-toolkit

  # Pip dependencies (everything else)
  - pip:
    # Model handling and acceleration
    - transformers>=4.44.0,<5.0.0
    - accelerate>=0.33.0,<1.0.0
    - safetensors>=0.4.0,<1.0.0
    
    # Compression and quantization
    - bitsandbytes>=0.41.0,<1.0.0
    - auto-gptq>=0.7.0,<1.0.0
    - peft>=0.12.0,<1.0.0
    
    # ModuLink integration
    - modulink-py
    
    # Data and monitoring
    - wandb>=0.17.0,<1.0.0
    - tensorboard>=2.17.0,<3.0.0
    - dvc>=3.51.0,<4.0.0
    - plotly>=5.17.0,<6.0.0
    
    # Development and testing
    - pytest>=8.2.0,<9.0.0
    - pytest-xdist>=3.3.0,<4.0.0
    - pytest-cov>=4.1.0,<5.0.0
    - pytest-mock>=3.11.0,<4.0.0
    - hypothesis>=6.100.0,<7.0.0
    
    # Code quality
    - black>=24.4.0,<25.0.0
    - ruff>=0.5.0,<1.0.0
    - mypy>=1.10.0,<2.0.0
    - pre-commit>=3.7.0,<4.0.0
    
    # Jupyter and notebooks
    - nbdime>=4.0.0,<5.0.0
    - ipywidgets>=8.1.0,<9.0.0
    - jupyterlab-git>=0.50.0,<1.0.0
    
    # Utilities
    - pyyaml>=6.0.0,<7.0.0
    - tqdm>=4.66.0,<5.0.0
    - rich>=13.7.0,<14.0.0
    - datasets>=2.20.0,<3.0.0
    - tokenizers>=0.19.0,<1.0.0

# Environment creation notes:
# 1. conda env create -f environment.yml
# 2. conda activate bird-bone-ai
# 3. Verify GPU: python -c "import torch; print(torch.cuda.is_available())"
#
# For CPU-only development:
# Change pytorch-cuda=12.4 to cpuonly
